# Gaussian Mixture Model
## Angus Mackenzie - 1106817
In this project we are tasked with creating a Gaussian Mixture Model (GMM) that can detect coins. It should be able to produce a mask that shows coin pixels in white and desk pixels in black. 

We need to run our code with 1-10 components and report the accuracy of our system. 

In [2]:
import numpy as np
from scipy import stats

$$
\begin{array}{l}{=\frac{\lambda_{k} \mathrm{Norm}_{\mathrm{x}_{i}}\left[\mu_{k}, \Sigma_{k}\right]}{\sum_{j=1}^{K} \lambda_{j} \operatorname{Norm}_{\mathrm{x}_{i}}\left[\mu_{j}, \Sigma_{j}\right]}} \\ {=r_{i k}}\end{array}
$$

In [3]:
# Test Data:
k = 2
𝜆 = np.array([0.5,0.5])
𝜎_2 = np.array([10,10])
𝜇 = np.array([250,20])
x_n = 5
x = np.array([255,255,1,3,3])
# k = 2
# 𝜆 = np.array([0.25,0.75])
# 𝜎_2 = np.array([10,10])
# 𝜇 = np.array([10,1])
# x_n = 5
# x = np.array([1,2,3,9,7])
# k = 2
# 𝜆 = np.array([0.5,0.5])
# 𝜎_2 = np.array([0.4,0.3])
# 𝜇 = np.array([0.50,0.75])
# x_n = 5
# x = np.array([0,0.1,1.1,1.2,0.3])

In [9]:
def e_step(k, 𝜆, 𝜎_2, 𝜇, x):
    for i in range(k):
        val = 𝜆[i]*stats.multivariate_normal.pdf(x, mean=𝜇[i], cov=𝜎_2[i])
        sum_components = 0
        for j in range(k):
            sum_components+=𝜆[j]*stats.multivariate_normal.pdf(x, mean=𝜇[j],cov=𝜎_2[j])
        print(np.round(val/sum_components,3))

In [10]:
e_step(k, 𝜆, 𝜎_2, 𝜇, x)

[1. 1. 0. 0. 0.]
[0. 0. 1. 1. 1.]


$$
\begin{aligned} \lambda_{k}^{[t+1]} &=\frac{\sum_{i=1}^{I} r_{i k}}{\sum_{j=1}^{K} \sum_{i=1}^{I} r_{i j}} \\ \boldsymbol{\mu}_{k}^{[t+1]} &=\frac{\sum_{i=1}^{I} r_{i k} \mathbf{x}_{i}}{\sum_{i=1}^{I} r_{i k}} \\ \boldsymbol{\Sigma}_{k}^{[t+1]} &=\frac{\sum_{i=1}^{I} r_{i k}\left(\mathbf{x}_{i}-\boldsymbol{\mu}_{k}^{[t+1]}\right)\left(\mathbf{x}_{i}-\boldsymbol{\mu}_{k}^{[t+1]}\right)^{T}}{\sum_{i=1}^{I} r_{i k}} \end{aligned}
$$

In [11]:
x_ri = np.array([0,0.1,1.1,1.2,0.3])
ri_0 = np.array([0.606, 0.593, 0.402, 0.378, 0.563])
ri_1 = np.array([0.394, 0.407, 0.598, 0.622, 0.437])
ris = np.array([ri_0,ri_1])

In [12]:
def m_step(x, k, riks):
    𝜆 = np.zeros((k))
    𝝁 = np.zeros((k))
    𝜎_2 = np.zeros((k))
    for i in range(k):
        𝜆[i] = np.sum(riks[i])/np.sum(riks)
        𝝁[i] = np.sum(riks[i]*x)/np.sum(riks[i])
        covar_sum = 0
        for j in range(len(x)):
            covar_sum += (riks[i][j] * (x[j]-𝝁[i])*(x[j]-𝝁[i]).T)/np.sum(riks[i])
        𝜎_2[i] = covar_sum
    return 𝜆, 𝝁, 𝜎_2

In [13]:
m_step(x_ri,2,ris)

(array([0.5084, 0.4916]),
 array([0.44217152, 0.64117168]),
 array([0.23223415, 0.26532686]))